### ISSUE TITLE
Document what is covered and what isn't

### ISSUE THREAD

**Issue by natebosch** [dart-lang/dart2_fix#10]
Hopefully we have some migration guide to link to for the set of changes we can't make automatically?

**Comment by devoncarew** [comment]
The sum total is currently deprecated constant renames, lightly documented here: https://github.com/dart-lang/dart2_fix#what-does-it-do

Totally agree that more comprehensive docs of what it can and can't do would be useful. Happy to take PRs here; @kevmoo may also want to upgrade the docs a bit

**Comment by devoncarew** [comment]
@leafpetersen, @lrhn assigning this to you. I imagine the migration guide should cover things like converting `JSON.encode` to either `jsonEncode` or `json.encode`.

**Comment by kwalrath** [comment]
We have a page, www.dartlang.org/dart-2 (latest version staged at https://kw-www-dartlang-1.firebaseapp.com/dart-2), where you can point people. It's not well populated yet, though, and might end up being a bunch of links.

**Comment by devoncarew** [comment]
Gotcha. I'll update the readme here to reference that page. You may want to mention this tool there, in terms of migrating deprecated constants.

**Comment by devoncarew** [comment]
fixed by https://github.com/dart-lang/dart2_fix/commit/01b690d2155c808fdda2227c83b87c66fb3714d6
