### ISSUE TITLE
Replaces `double.INFINITY` with `DateTime.infinity`.

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dart2_fix#11]
Against https://github.com/dart-lang/angular_components

Replaces `double.INFINITY` with `DateTime.infinity`.

v/ v1.0.0

**Comment by devoncarew** [comment]
I'll also note that this doesn't speak to the nature of infinity.

**Comment by devoncarew** [comment]
published the fixed version: https://github.com/dart-lang/dart2_fix/releases/tag/1.0.0%2B1
