### ISSUE TITLE
Add support for dart2_constant

### ISSUE THREAD

**Issue by nex3** [dart-lang/dart2_fix#18]
The [`dart2_constant`](https://github.com/dart-lang/dart2_constant) package provides camel-case constant definitions that work on both Dart 1 and Dart 2, for packages that want to support both. It would be great if this package could add support for migrating to uses of these polyfill constants in addition to using the Dart 2 constants directly.

**Comment by devoncarew** [comment]
Ah, migrating from `package:dart2_constant`'s `utf8` to `dart:convert`'s `utf8`?

**Comment by nex3** [comment]
That, but also migrating from Dart 1's `UTF8` to `package:dart2_constant`'s `convert.utf8`.

**Comment by devoncarew** [comment]
Thanks for the suggestion; I think I'm going to mark this as out of scope for this package.
